# Generated by Django 3.2.10 on 2021-12-11 02:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Created Date'),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_city',
            field=models.SmallIntegerField(choices=[(0, 'Beijing'), (1, 'Shanghai'), (2, 'Shenzhen'), (3, 'Hangzhou'), (4, 'Guangzhou')], verbose_name='JOB City'),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_requirement',
            field=models.TextField(max_length=1024, verbose_name='JOB Requirement'),
        ),
        migrations.AlterField(
            model_name='job',
            name='modified_date',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Modified Date'),
        ),
    ]
