# Generated by Django 3.2.10 on 2021-12-11 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.IntegerField(blank=True, null=True, unique=True, verbose_name='ID')),
                ('username', models.CharField(max_length=135, verbose_name='Name')),
                ('city', models.CharField(max_length=135, verbose_name='City')),
                ('telephone', models.CharField(max_length=135, verbose_name='Telephone')),
                ('email', models.EmailField(blank=True, max_length=135, verbose_name='Email')),
                ('apply_position', models.CharField(blank=True, max_length=135, verbose_name='Apply Position')),
                ('born_address', models.CharField(blank=True, max_length=135, verbose_name='Born Address')),
                ('gender', models.CharField(blank=True, max_length=135, verbose_name='Gender')),
                ('candidate_remark', models.CharField(blank=True, max_length=135, verbose_name='Candidate Remark')),
                ('bachelor_school', models.CharField(blank=True, max_length=135, verbose_name='Bachelor School')),
                ('master_school', models.CharField(blank=True, max_length=135, verbose_name='Master School')),
                ('doctor_school', models.CharField(blank=True, max_length=135, verbose_name='Doctor School')),
                ('major', models.CharField(blank=True, max_length=135, verbose_name='Major')),
                ('degree', models.CharField(blank=True, choices=[('本科', '本科'), ('硕士', '硕士'), ('博士', '博士')], max_length=135, verbose_name='Degree')),
                ('test_score_of_general_ability', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='General Ability Score')),
                ('paper_score', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='Paper Score')),
                ('first_score', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='First Score')),
                ('first_learning_ability', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True, verbose_name='Learning Ability Score')),
                ('first_profession_competency', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True, verbose_name='Profession Competency Score')),
                ('first_advantage', models.TextField(blank=True, max_length=1024, verbose_name='Advantage')),
                ('first_disadvantage', models.TextField(blank=True, max_length=1024, verbose_name='Disadvantage')),
                ('first_result', models.CharField(blank=True, choices=[('建议复试', '建议复试'), ('待定', '待定'), ('放弃', '放弃')], max_length=256, verbose_name='First Interview Result')),
                ('first_recommend_position', models.CharField(blank=True, max_length=256, verbose_name='Recommend Position')),
                ('first_interviewer', models.CharField(blank=True, max_length=256, verbose_name='Interviewer')),
                ('first_remark', models.CharField(blank=True, max_length=135, verbose_name='First Interview Remark')),
                ('second_score', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='Second Score')),
                ('second_learning_ability', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True, verbose_name='Learning Ability Score')),
                ('second_profession_competency', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True, verbose_name='Profession Competency Score')),
                ('second_pursue_of_excellence', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True, verbose_name='Excellence Pur Score')),
                ('second_communication_ability', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True, verbose_name='Communication Ability Score')),
                ('second_pressure_score', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True, verbose_name='Pressure Score')),
                ('second_advantage', models.TextField(blank=True, max_length=1024, verbose_name='Advantage')),
                ('second_disadvantage', models.TextField(blank=True, max_length=1024, verbose_name='Disadvantage')),
                ('second_result', models.CharField(blank=True, choices=[('建议复试', '建议复试'), ('待定', '待定'), ('放弃', '放弃')], max_length=256, verbose_name='Second Interview Result')),
                ('second_recommend_position', models.CharField(blank=True, max_length=256, verbose_name='Recommend Position')),
                ('second_interviewer', models.CharField(blank=True, max_length=256, verbose_name='Interviewer')),
                ('second_remark', models.CharField(blank=True, max_length=135, verbose_name='Second Interview Remark')),
                ('HR_score', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='HR Score')),
                ('HR_responsibility', models.CharField(blank=True, choices=[('S', 'S'), ('A', 'A'), ('B', 'B'), ('C', 'C')], max_length=10, verbose_name='HR Responsibility')),
                ('HR_communication_ability', models.CharField(blank=True, choices=[('S', 'S'), ('A', 'A'), ('B', 'B'), ('C', 'C')], max_length=10, verbose_name='HR Communication Ability Score')),
                ('HR_logic_ability', models.CharField(blank=True, choices=[('S', 'S'), ('A', 'A'), ('B', 'B'), ('C', 'C')], max_length=10, verbose_name='HR Logic Ability Score')),
                ('HR_potential', models.CharField(blank=True, choices=[('S', 'S'), ('A', 'A'), ('B', 'B'), ('C', 'C')], max_length=10, verbose_name='HR Potential Score')),
                ('HR_stability', models.CharField(blank=True, choices=[('S', 'S'), ('A', 'A'), ('B', 'B'), ('C', 'C')], max_length=10, verbose_name='HR Stability Score')),
                ('HR_advantage', models.TextField(blank=True, max_length=1024, verbose_name='Advantage')),
                ('HR_disadvantage', models.TextField(blank=True, max_length=1024, verbose_name='Disadvantage')),
                ('HR_result', models.CharField(blank=True, choices=[('建议复试', '建议复试'), ('待定', '待定'), ('放弃', '放弃')], max_length=256, verbose_name='HR Interview Result')),
                ('HR_interviewer', models.CharField(blank=True, max_length=256, verbose_name='HR Interviewer')),
                ('HR_remark', models.CharField(blank=True, max_length=256, verbose_name='HR Interview Remark')),
                ('creator', models.CharField(blank=True, max_length=256, verbose_name='Creator')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('modifed_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Update Date')),
                ('last_editor', models.CharField(blank=True, max_length=256, verbose_name='Last Editor')),
            ],
            options={
                'verbose_name': '应聘者',
                'verbose_name_plural': '应聘者',
                'db_table': 'candidate',
            },
        ),
    ]
